server:
  port: 80

spring:
  application:
    name: spring-cloud-eureka-feign-client80

eureka:
  client:
    service-url:
      defaultZone: http://localhost10012:10012/eureka/,http://localhost10013:10013/eureka/