server:
  port: 80
spring:
  application:
    name: spring-cloud-eureka-hystrix-client80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/
    register-with-eureka: false

feign:
  circuitbreaker:
    enabled: true