spring:
  application:
    name: spring-cloud-eureka-balance-server

server:
  port: 10012
#  eureka 服务配置
eureka:
  instance:
    hostname: localhost10012
  client:
    service-url:
      defaultZone: http://localhost10013:10013/eureka/

