server:
  port: 80
spring:
  application:
    name: spring-cloud-eureka-balance-client80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10012/eureka/,http://localhost:10013/eureka/

