server:
  port: 10016

spring:
  application:
    name: spring-cloud-eureka-hystrix-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/
    fetch-registry: true
    register-with-eureka: true