server:
  port: 10014

spring:
  application:
    name: spring-cloud-eureka-balance-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost10012:10012/eureka/,http://localhost10013:10013/eureka/
